version: '3.8'

services:
  front:
    container_name: platform_front
    env_file:
      - .env
    build:
      context: .
    ports:
      - ${REACT_APP_PORT}:80
    networks:
      - platform-network

networks:
  platform-network:
    driver: bridge

