export const FETCH_ACCRUALS = 'FETCH_ACCRUALS';
export const SET_ACCRUALS = 'SET_ACCRUALS';

export const FETCH_ACCRUALS_INCOME = 'FETCH_ACCRUALS_INCOME';
export const SET_ACCRUALS_INCOME = 'SET_ACCRUALS_INCOME';
