const countries = [
  {
    options: [
      { label: "Россия", value: "RU" },
      { label: "Казахстан", value: "KZ" },
      { label: "Абхазия", value: "AB" },
      { label: "Австрия", value: "AT" },
      { label: "Азербайджан", value: "AZ" },
      { label: "Албания", value: "AL" },
      { label: "Андорра", value: "AD" },
      { label: "Армения", value: "AM" },
      { label: "Афганистан", value: "AF" },
      { label: "Бангладеш", value: "BD" },
      { label: "Бахрейн", value: "BH" },
      { label: "Беларусь", value: "BY" },
      { label: "Бельгия", value: "BE" },
      { label: "Болгария", value: "BG" },
      { label: "Босния и Герцеговина", value: "BA" },
      { label: "Бруней-Даруссалам", value: "BN" },
      { label: "Бутан", value: "BT" },
      { label: "Венгрия", value: "HU" },
      { label: "Вьетнам", value: "VN" },
      { label: "Германия", value: "DE" },
      { label: "Гернси", value: "GG" },
      { label: "Гибралтар", value: "GI" },
      { label: "Гонконг", value: "HK" },
      { label: "Греция", value: "GR" },
      { label: "Грузия", value: "GE" },
      { label: "Дания", value: "DK" },
      { label: "Джерси", value: "JE" },
      { label: "Израиль", value: "IL" },
      { label: "Индия", value: "IN" },
      { label: "Индонезия", value: "ID" },
      { label: "Иордания", value: "JO" },
      { label: "Ирак", value: "IQ" },
      { label: "Иран, Исламская Республика", value: "IR" },
      { label: "Ирландия", value: "IE" },
      { label: "Исландия", value: "IS" },
      { label: "Испания", value: "ES" },
      { label: "Италия", value: "IT" },
      { label: "Йемен", value: "YE" },
      { label: "Камбоджа", value: "KH" },
      { label: "Катар", value: "QA" },
      { label: "Кипр", value: "CY" },
      { label: "Киргизия", value: "KG" },
      { label: "Китай", value: "CN" },
      { label: "Корея, Народно-Демократическая Республика", value: "KP" },
      { label: "Корея, Республика", value: "KR" },
      { label: "Кувейт", value: "KW" },
      { label: "Лаос", value: "LA" },
      { label: "Латвия", value: "LV" },
      { label: "Ливан", value: "LB" },
      { label: "Лихтенштейн", value: "LI" },
      { label: "Литва", value: "LT" },
      { label: "Люксембург", value: "LU" },
      { label: "Макао", value: "MO" },
      { label: "Малайзия", value: "MY" },
      { label: "Мальдивы", value: "MV" },
      { label: "Мальта", value: "MT" },
      { label: "Молдова, Республика", value: "MD" },
      { label: "Монако", value: "MC" },
      { label: "Монголия", value: "MN" },
      { label: "Мьянма", value: "MM" },
      { label: "Непал", value: "NP" },
      { label: "Нидерланды", value: "NL" },
      { label: "Норвегия", value: "NO" },
      { label: "Объединенные Арабские Эмираты", value: "AE" },
      { label: "Оман", value: "OM" },
      { label: "Остров Мэн", value: "IM" },
      { label: "Пакистан", value: "PK" },
      { label: "Палестинская территория, оккупированная", value: "PS" },
      { label: "Папский Престол (Государство &mdash; город Ватикан)", value: "VA" },
      { label: "Польша", value: "PL" },
      { label: "Португалия", value: "PT" },
      { label: "Республика Македония", value: "MK" },
      { label: "Румыния", value: "RO" },
      { label: "Сан-Марино", value: "SM" },
      { label: "Саудовская Аравия", value: "SA" },
      { label: "Сербия", value: "RS" },
      { label: "Сингапур", value: "SG" },
      { label: "Сирийская Арабская Республика", value: "SY" },
      { label: "Словакия", value: "SK" },
      { label: "Словения", value: "SI" },
      { label: "Соединенное Королевство", value: "GB" },
      { label: "Таджикистан", value: "TJ" },
      { label: "Таиланд", value: "TH" },
      { label: "Тайвань (Китай)", value: "TW" },
      { label: "Тимор-Лесте", value: "TL" },
      { label: "Туркмения", value: "TM" },
      { label: "Турция", value: "TR" },
      { label: "Узбекистан", value: "UZ" },
      { label: "Украина", value: "UA" },
      { label: "Фарерские острова", value: "FO" },
      { label: "Филиппины", value: "PH" },
      { label: "Финляндия", value: "FI" },
      { label: "Франция", value: "FR" },
      { label: "Хорватия", value: "HR" },
      { label: "Черногория", value: "ME" },
      { label: "Чешская Республика", value: "CZ" },
      { label: "Швейцария", value: "CH" },
      { label: "Швеция", value: "SE" },
      { label: "Шпицберген и Ян Майен", value: "SJ" },
      { label: "Шри-Ланка", value: "LK" },
      { label: "Эландские острова", value: "AX" },
      { label: "Эстония", value: "EE" },
      { label: "Южная Осетия", value: "OS" },
      { label: "Япония", value: "JP" },
    ],
  },
]

export default countries

export const countryName = countries[0].options.reduce((acc, curr) => {
  acc[curr.value] = curr.label
  return acc
}, {})
