export const GET_TEAM_INFO = 'GET_TEAM_INFO';
export const GET_PARTNERS_INCOME = 'GET_PARTNERS_INCOME';
export const SET_PARTNERS_INCOME_RANGE = 'SET_PARTNERS_INCOME_RANGE';
export const GET_PARTNERS = 'GET_PARTNERS';
